### ISSUE TITLE
Gulp Build Error, Angular / Bower

### ISSUE THREAD

**Issue by codeThaGlobe** [olov/ng-annotate#121]
Error in plugin 'gulp-ng-annotate'
scripts/app-92785c13.js: error: couldn't process source due to parse error
Line 848: Delete of an unqualified identifier in strict mode.
at Transform._transform (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/index.js:34:26)
at Transform._read (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
at Transform._write (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
at doWrite (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
at writeOrBuffer (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
at Transform.Writable.write (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
at write (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
at flow (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
at DestroyableTransform.pipeOnReadable (/Users/user_name/Work/dev/folder_name/2015/node_modules/gulp-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
at DestroyableTransform.emit (events.js:92:17)

**Comment by shashvattrip** [comment]
Hey, I get the same error but different line. How do I check which line the error at? I can't find Line 848 as there's no such file. What's the best way to go about debugging such errors.
